# 比较两个字符串的相似度

量化方法： **编辑距离(Edit  Distance)**

- 莱文斯坦距离(Levenshtein distance): 允许**增加、删除、替换**字符三个操作
- 最长公共子串长度(Longest common substring length): 允许**增加、删除**两个操作

In [45]:
''' 莱文斯坦距离 '''


import numpy as np


str1 = 'mitcmu'
str2 = 'mtacnu'


def lvstDP(str1, str2):
    minState = np.array([[0]*len(str2) for x in range(len(str1))])
    for index in range(len(str1)):
        if str2[0] == str1[index]:
            minState[index, 0] = index
        elif index != 0:
            minState[index, 0] = minState[index-1, 0] + 1
        else:
            minState[index, 0] = 1
    for index in range(len(str2)):
        if str1[0] == str2[index]:
            minState[0, index] = index
        elif index != 0:
            minState[0, index] = minState[0, index-1] + 1
        else:
            minState[0, index] = 1

    print(minState)

    for n1 in range(1, len(str1)):
        for n2 in range(1, len(str2)):
            if str1[n1] == str2[n2]:
                minState[n1, n2] = min(
                    minState[n1-1, n2] + 1,
                    minState[n1, n2-1] + 1,
                    minState[n1-1, n2-1])
            else:
                minState[n1, n2] = min(
                    minState[n1-1, n2] + 1,
                    minState[n1, n2-1] + 1,
                    minState[n1-1, n2-1] + 1)
        print('-'*20)
        print(minState)

        
lvstDP(str1, str2)

[[0 1 2 3 4 5]
 [1 0 0 0 0 0]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
--------------------
[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 0 0 0 0 0]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
--------------------
[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 1 2 3 4 5]
 [3 0 0 0 0 0]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
--------------------
[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 1 2 3 4 5]
 [3 2 2 2 3 4]
 [4 0 0 0 0 0]
 [5 0 0 0 0 0]]
--------------------
[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 1 2 3 4 5]
 [3 2 2 2 3 4]
 [4 3 3 3 3 4]
 [5 0 0 0 0 0]]
--------------------
[[0 1 2 3 4 5]
 [1 1 2 3 4 5]
 [2 1 2 3 4 5]
 [3 2 2 2 3 4]
 [4 3 3 3 3 4]
 [5 4 4 4 4 3]]


In [53]:
''' 最长公共子串长度 '''


import numpy as np


str1 = 'mitcmu'
str2 = 'mtacnu'


def lvstDP(str1, str2):
    minState = np.array([[0]*len(str2) for x in range(len(str1))])
    for index in range(len(str1)):
        if index != 0:
            minState[index, 0] = minState[index-1, 0]
        else:
            minState[index, 0] = 1 if str2[0] == str1[index] else 0
    for index in range(len(str2)):
        if index != 0:
            minState[0, index] = minState[0, index-1]
        else:
            minState[0, index] = 1 if str2[0] == str1[index] else 0

    print(minState)

    for n1 in range(1, len(str1)):
        for n2 in range(1, len(str2)):
            if str1[n1] == str2[n2]:
                minState[n1, n2] = max(
                    minState[n1-1, n2],
                    minState[n1, n2-1],
                    minState[n1-1, n2-1] + 1)
            else:
                minState[n1, n2] = max(
                    minState[n1-1, n2],
                    minState[n1, n2-1],
                    minState[n1-1, n2-1])
        print('-'*20)
        print(minState)


lvstDP(str1, str2)

[[1 1 1 1 1 1]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
--------------------
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
--------------------
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 2 2 2 2 2]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
--------------------
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 2 2 2 2 2]
 [1 2 2 3 3 3]
 [1 0 0 0 0 0]
 [1 0 0 0 0 0]]
--------------------
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 2 2 2 2 2]
 [1 2 2 3 3 3]
 [1 2 2 3 3 3]
 [1 0 0 0 0 0]]
--------------------
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 2 2 2 2 2]
 [1 2 2 3 3 3]
 [1 2 2 3 3 3]
 [1 2 2 3 3 4]]
