# 动态规划(Dynamic Programming)

In [24]:
''' 0-1背包 '''


weight = [2, 2, 3, 6, 3]
count = len(weight)
MAX_WEIGHT = 9


def knapsack(weight:list, count:int, MAX_WEIGHT:int):
    state = [False for x in range(MAX_WEIGHT+1)]
    state[0] = True
    for index, _weight in enumerate(weight):
        # 放进背包
        for new_weight in range(MAX_WEIGHT-_weight, -1, -1):
            if state[new_weight]:
                state[new_weight + _weight] = True
        print('%s: %s' %(index, state))
        
    for x in range(MAX_WEIGHT, -1, -1):
        if state[x]:
            return x

knapsack(weight_list, count, MAX_WEIGHT)

0: [True, False, True, False, False, False, False, False, False, False]
1: [True, False, True, False, True, False, False, False, False, False]
2: [True, False, True, True, True, True, False, True, False, False]
3: [True, False, True, True, True, True, True, True, True, True]
4: [True, False, True, True, True, True, True, True, True, True]


9

In [83]:
''' 0-1背包: 物品有质量 '''

import numpy as np


weight = [2, 2, 3, 6, 3]
value = [3, 4, 8, 9, 6]
count = len(weight)
MAX_WEIGHT = 9


def knapsack(weight:list, count:int, MAX_WEIGHT:int):
    # state[index:weight] = total_value
    state = np.array([[-1]*10 for x in range(count)])
    state[0,0] = 0
    state[0, weight[0]] = value[0]
    print('%s:\n%s' %(0, state))
    print('-'*20)
    for index, new_weight in enumerate(weight[1:], start=1):
        print('%s:' % index)

        # 第index个物品不放背包
        for _weight, _value in enumerate(state[index-1]):
            if _value >= 0:
                state[index][_weight] = _value
        print(state)
        
        # 第index个物品放进背包
        for _weight, _last_value in enumerate(state[index-1]):
            if _last_value >= 0 and _weight+new_weight < MAX_WEIGHT:
                _value = _last_value + value[index]
                if _value > state[index][_weight+new_weight]:
                    state[index][_weight+new_weight] = _value

        print(state)
        print('-'*20)
        
    return state.max()


knapsack(weight_list, count, MAX_WEIGHT)

0:
[[ 0 -1  3 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
--------------------
1:
[[ 0 -1  3 -1 -1 -1 -1 -1 -1 -1]
 [ 0 -1  3 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
[[ 0 -1  3 -1 -1 -1 -1 -1 -1 -1]
 [ 0 -1  4 -1  7 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
--------------------
2:
[[ 0 -1  3 -1 -1 -1 -1 -1 -1 -1]
 [ 0 -1  4 -1  7 -1 -1 -1 -1 -1]
 [ 0 -1  4 -1  7 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
[[ 0 -1  3 -1 -1 -1 -1 -1 -1 -1]
 [ 0 -1  4 -1  7 -1 -1 -1 -1 -1]
 [ 0 -1  4  8  7 12 -1 15 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]]
--------------------
3:
[[ 0 -1  3 -1 -1 -1 -1 -1 -1 -1]
 [ 0 -1  4 -1  7 -1 -1 -1 -1 -1]
 [ 0 -1  4  8  7 12 -1 15 -1 

18

In [22]:
''' 硬币

三种不同硬币（1、3、5），支付9元，最少给多少个硬币？
'''

values = [1, 3, 5]
total = 9

def pay(total, values):
    state = [0 for x in range(total+1)]

    for value in range(1, total+1):
        if value in values:
            # 哨兵
            state[value] = 1
        else:
            # 找状态表，能找到的话就取这个状态的硬币数量出来。
            _count = (state[value-x] for x in values if value-x > 0 and state[value-x] > 0)
            state[value] = min(_count) + 1
            
    print('state: %s' % state)
            
pay(total, values)
        

state: [0, 1, 2, 1, 2, 1, 2, 3, 2, 3]
